kind: CheCluster
apiVersion: org.eclipse.che/v2
metadata:
  name: devspaces
spec:
  components:
    dashboard:
      headerMessage:
        show: true
        text: >-
          Welcome To the RH OpenShift Dev Spaces Lab. Enjoy!
  containerRegistry: {}
  devEnvironments:
    disableContainerBuildCapabilities: false
    storage:
      pvcStrategy: 'per-workspace'
  gitServices: {}
  networking: {}

